name: MagicCamera
favicon: null
layout_spectrum: 0.25363
typography_spectrum: 0.24606
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ec3a27'
    - '#ffffff'
    - '#f7ac97'
    - '#6d3e37'
    - '#1d0b07'
  brandStrength: 0.5
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
