name: MagicCamera
favicon: null
layout_spectrum: 0
typography_spectrum: 0.32472
title: MagicCamera Design Services
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#393a35'
    - '#ffffff'
    - '#656658'
    - '#c28400'
    - '#ffc400'
  brandStrength: 0.5
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
